### ISSUE TITLE
macports installation failed (missing noahstrap)

### ISSUE THREAD

**Issue by axet** [linux-noah/noah#104]
axet-laptop:noah axet$ noah 
Noah is installing the initial filesystem in ~/.noah/tree. Proceed? [Y/n] 
sudo: noahstrap: command not found
Invalid --mnt flag: : No such file or directory

**Comment by ryandesign** [comment]
Install https://github.com/linux-noah/noahstrap first.

**Comment by axet** [comment]
tx
