### ISSUE TITLE
noah aborts with "read_vmcs failed"

### ISSUE THREAD

**Issue by saagarjha** [linux-noah/noah#37]
I'm having trouble getting noah to work on my computer, since it keeps aborting whenever `hv_vmx_vcpu_read_vmcs` returns an error. Poking around, it looks like it fails with a `HV_ERROR` when it calls the method with `VMCS_HOST_IA32_SYSENTER_ESP` or `VMCS_HOST_IA32_SYSENTER_EIP` as the `field`, but I'm not sure why this is happening.

**Comment by xenexis** [comment]
Same here. MacOS High Sierra (10.13)

**Comment by dphov** [comment]
MacOS High Sierra (10.13.2)
bash 4.4.12
`$ noah`
```bash
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (ru_RU.UTF-8): No such file or directory
bash: /opt/bin/env: No such file or directory
read_vmcs failed
```

**Comment by MJBOLDUC** [comment]
Have a similar issue, getting "read_vmcs failed" with "$ noah" if in source dir and use "noah ./binary" it returns to prompt.  this output of "file" on binary...
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=e085da6d3985ab3f928767e81702aca7e3b90c32, with debug_info, not stripped

**Comment by FrostyModz** [comment]
same issue here

**Comment by MichalMares** [comment]
Same, is anybody looking into this?

**Comment by utshina** [comment]
This issue (read_vmcs failed) is already fixed in the latest source code. Please build a binary from the source code until a new version is released.

**Comment by saagarjha** [comment]
Yes, this issue is gone for me at least when compiling from the master branch. I'm going to close this issue.
