### ISSUE TITLE
Run existing distro mounted in directory ?

### ISSUE THREAD

**Issue by stuaxo** [linux-noah/noah#38]
I mount my real Ubuntu with fuse OS X at ```/Volumes/Ubuntu``` how can I get Noah to use it (I don't mind that this may be living dangerously).

**Comment by melvyn2** [comment]
Try to use `/usr/local/libexec/noah -m /Volumes/Ubuntu /bin/bash`

**Comment by stuaxo** [comment]
Mac is broken at the moment, and not sure if I will fix it, so I'm going to close this.

If this does work it could be worth documenting.

**Comment by stuaxo** [comment]
Thanks for the info though, probably will use it when I next have a mac.
