### ISSUE TITLE
Passing command line arguments to the executables

### ISSUE THREAD

**Issue by tpimh** [linux-noah/noah#51]
If I run `noah .noah/tree/bin/sh`, it's fine, but what if want to run `/bin/sh -i -E`? How do I do it?

Here is what I tried and what I got:
```
noah .noah/tree/bin/sh -i -E
Unknown option: i
Unknown option: e
```

**Comment by nullpo-head** [comment]
Thanks for trying Noah.
You can pass arguments after ``--`` like ``noah .noah/tree/bin/sh -- -i -E`` .

**Comment by tpimh** [comment]
Thank you!
